name: Generate and publish docs

on:
  push:
    branches:
      - "more-documentation"
#      - "spark-3.2"-
  pull_request:
    branches:
      - "more-documentation"
#      - "spark-3.2"


jobs:
  generate-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distributions: adopt
          java-version: 11
          check-latest: true
      - name: Generate docs
        run: ./mvnw clean package site -Dmaven.test.skip=true
      - name: Copy docs to "docs" branch
        env:
          SRC_FOLDER: "kotlin-spark-api/3.2/target/dokka"
          TARGET_BRANCH: "origin/docs"
        run: |
          files=$(find $SRC_FOLDER -type f) # get the file list
          git add ${files}/*
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "updated docs"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
